p8105_hw2_lz2950
================
Lehan Zou
2023-10-01

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.5 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.1      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.3      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(dplyr)
library(readxl)
```

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )

pols = 
  read.csv("~/Desktop/DS/P8105_HW2/data/fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  left_join(x = _, y = month_df) |> 
  select(year, month, everything(), -day, -starts_with("prez")) 
```

    ## Joining, by = "month_num"

``` r
#read csv file
snp <- read.csv("~/Desktop/DS/P8105_HW2/data/fivethirtyeight_datasets/snp.csv") |>
  separate(date, into = c("month", "day", "year"), convert = TRUE) |>
  mutate(year = ifelse(year>=50, 1900+year, 2000+year), )|>
  arrange(year, month) |>
  mutate(month = month.name[month]) |>
  select(year, month, close) 
```

``` r
unemployment = 
  read_csv("~/Desktop/DS/P8105_HW2/data/fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining, by = "month_abb"

Now we merge the three datasets!

``` r
data_538 = 
  left_join(pols, snp) |>
  left_join(x = _, y = unemployment)
```

    ## Joining, by = c("year", "month")
    ## Joining, by = c("year", "month")

``` r
str(data_538)
```

    ## 'data.frame':    822 obs. of  13 variables:
    ##  $ year        : num  1947 1947 1947 1947 1947 ...
    ##  $ month       : chr  "January" "February" "March" "April" ...
    ##  $ month_num   : int  1 2 3 4 5 6 7 8 9 10 ...
    ##  $ gov_gop     : int  23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : int  51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : int  253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : int  23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : int  45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : int  198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president   : chr  "dem" "dem" "dem" "dem" ...
    ##  $ month_abb   : chr  "Jan" "Feb" "Mar" "Apr" ...
    ##  $ close       : num  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num  NA NA NA NA NA NA NA NA NA NA ...

### Problem 2

``` r
#read csv file
Mr_trash_wheel <- read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = cell_cols("A2:N586"), col_names = TRUE, trim_ws = TRUE, skip = 1) |>
  # use reasonable variable names
  janitor::clean_names() |>
  # omit rows that do not include dumpster-specific data
  filter(!is.na(dumpster)) |>
  mutate(homes_powered = weight_tons * 500 / 30,
         year = as.numeric(year), 
         name = "Mr Trash Wheel") 
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
prof_trash_wheel <- read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = cell_cols("A2:M108")) |>
  # use reasonable variable names
  janitor::clean_names() |>
  # omit rows that do not include dumpster-specific data
  filter(!is.na(dumpster)) |>
  mutate(homes_powered = weight_tons * 500 / 30,
         name = "Professor Trash Wheel") 
```

``` r
gwy_trash_wheel <- read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = cell_cols("A2:L157"), col_names = TRUE, trim_ws = TRUE, skip = 1) |>
  # use reasonable variable names
  janitor::clean_names() |>
  # omit rows that do not include dumpster-specific data
  filter(!is.na(dumpster)) |>
  mutate(homes_powered = weight_tons * (500 / 30),
         name = "Gwynnda Trash Wheel") 
```

Then we can combine those three data set.

``` r
trash_wheel <-
  Mr_trash_wheel |> 
  full_join(prof_trash_wheel) |> 
  full_join(gwy_trash_wheel) |> 
  relocate(name)
```

    ## Joining, by = c("dumpster", "month", "year", "date", "weight_tons",
    ## "volume_cubic_yards", "plastic_bottles", "polystyrene", "cigarette_butts",
    ## "glass_bottles", "plastic_bags", "wrappers", "homes_powered", "name")
    ## Joining, by = c("dumpster", "month", "year", "date", "weight_tons",
    ## "volume_cubic_yards", "plastic_bottles", "polystyrene", "cigarette_butts",
    ## "glass_bottles", "plastic_bags", "wrappers", "homes_powered", "name")

The cleaned “Mr. Trash Wheel” data set has 584 observations of 17
variables and tells us about the trash collected by trash wheel from
May, 2014 to June, 2023. The cleaned “Professor Trash Wheel” data set
contains 106 observations of 14 variables from January, 2017 to June,
2023. The cleaned “Gwynnda Trash Wheel” data set contains 106
observations of 14 variables from January, 2017 to June, 2023.  
For the combined dataset, it contains 796 observations of 17 variables,
among which the `name` variable marks the trash wheel’s name (Mr Trash
Wheel, Professor Trash Wheel, Gwynnda Trash Wheel).

``` r
professor_sum_weight = sum(pull(prof_trash_wheel, weight_tons))
gwy_ciga_butts = gwy_trash_wheel |> filter(year == 2021 & month == "July") |> pull(cigarette_butts) |> sum()
```

The total weight of trash collected by Professor Trash Wheel is 216.26
and the total number of cigarette butts collected by Gwynnda in July of
2021 is 1.56^{4}.

### Problem 3

``` r
#read csv file
mci_baseline <-
  read_csv("data/data_mci/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |>
  mutate(
    #recode sex and apoe4 to non-numeric variables
    sex = recode(sex,
                 "1" = "Male",
                 "0" = "Female"),
    apoe4 = recode(apoe4,
                   "1" = "Carrier",
                   "0" = "Non-carrier")) |>
  #remove participants who do not meet the stated inclusion criteria
  filter(age_at_onset == "."|current_age < age_at_onset )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

For the data cleaning, first I skipped the first row which contains
notes for the columns. I used recode() function to convert the numerical
values of `sex` and `apoe4` to their actual meaning. Lastly, I remove
participants who do not meet the stated inclusion criteria by selecting
the `current_age` variable smaller than `age_at_onset` variable. After
cleaning, the data set contains 479 observations of 6 variables.

From the data set, it could be concluded that 483 participants in total
were recruited, and 479 participants met the criteria, 479 develop MCI.
The average baseline age is 65.0286013, and 30% of women in the study
are APOE4 carriers.

Next, I’m going to import the data set of longitudinally observed
bionnarker values.

``` r
#read amyloid csv file
amyloid <-
  read_csv("data/data_mci/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names() |>
  rename(id = study_id) |>
  pivot_longer(baseline:time_8,
               names_prefix="time_",
               names_to="years_since_diagnosed",
               values_to="amyloid_ratio") |>
               #change baseline to 0 and convert amyloid ratio to numerical variable
               mutate(
    years_since_diagnosed =
      replace(years_since_diagnosed,years_since_diagnosed == "baseline",0),
    amyloid_ratio = as.numeric(amyloid_ratio) 
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning in mask$eval_all_mutate(quo): NAs introduced by coercion

``` r
amyloid
```

    ## # A tibble: 2,435 × 3
    ##       id years_since_diagnosed amyloid_ratio
    ##    <dbl> <chr>                         <dbl>
    ##  1     1 0                             0.111
    ##  2     1 2                            NA    
    ##  3     1 4                             0.109
    ##  4     1 6                             0.105
    ##  5     1 8                             0.107
    ##  6     2 0                             0.107
    ##  7     2 2                             0.109
    ##  8     2 4                             0.109
    ##  9     2 6                             0.106
    ## 10     2 8                             0.107
    ## # … with 2,425 more rows

For the data set mci_amyloid, first I read in csv file and skip the
first line, input only data entries along with variable names. Then I
used `clean_names()` to make sure the names are unique and consistent.
Also I renamed variable “study_id” to “id”. Then I use “pivot_longer” to
change the original data from horizontal to vertical with the variable
(baseline:times_8) becomes “years_since_diagnosed”. Moreover, I renamed
baseline to 0 and changed “amyloid_ratio” to numeric variable. After
cleaning, There are 2435 observations of 3 variables.

``` r
#use anti_join() function to find unmatched cases

unmatched_baseline = anti_join(mci_baseline, amyloid, by = "id")

unmatched_amyloid = anti_join(amyloid, mci_baseline, by = "id")
```

There are 8 for participants appear only in baseline data set and 16
appear only in amyloid data set.

``` r
mci_combined <-
  inner_join(mci_baseline, amyloid, by= "id")
#write data to a csv file  
write_csv(mci_combined, "data/data_mci/mci_combined.csv")
```

There are 471 participants appear in both dataset, each participants
have 5 rows data. So total 2355 in the combined dataset.
